name: Render and deploy
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write
jobs:
  render-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout ğŸ›ï¸
#        uses: actions/checkout@v3

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: "" # If set, it will be equivalent to `quarto render --to html`
          path: . # By default, the current working dir is used i.e `quarto render .`

#      - name: Deploy ğŸš€
#        uses: JamesIves/github-pages-deploy-action@v4
#        with:
#          folder: docs # The folder the action should deploy.
